#running shell script with github workflow
name: Check for push
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
        run: ./list-ADOonprem-repositories.sh
    
        
        -name: printing the list
         run: | echo Here is the list
               ls -a
               pwd
        
        
        ##shell: bash
