#running shell script with github workflow
name: Check for push
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
        
    
        
      - name: Running migrate script(new)
        run: |
          bash migrate-repositories-to-github.sh ado_repositories.csv
       
        
        
    
